require "bundler/gem_tasks"
require "rspec/core/rake_task"

RSpec::Core::RakeTask.new(:spec)

require "rake/extensiontask"

task :build => :compile

Rake::ExtensionTask.new("yoga_layout") do |ext|
  ext.lib_dir = "lib/yoga_layout"
end

task :copy_src do
  sh 'cp ../yoga/* ext/yoga_layout'
end

task :default => [:copy_src, :clobber, :compile, :spec]
