# This file is auto-generated by //enums.py
# Do not edit by hand!
module YogaLayout
  module Native
    include FFI::Library

    Align = enum(
      :Auto,
      :FlexStart,
      :Center,
      :FlexEnd,
      :Stretch,
      :Baseline,
      :SpaceBetween,
      :SpaceAround,
    )
    typedef Align, :YGAlign

    Dimension = enum(
      :Width,
      :Height,
    )
    typedef Dimension, :YGDimension

    Direction = enum(
      :Inherit,
      :LTR,
      :RTL,
    )
    typedef Direction, :YGDirection

    Display = enum(
      :Flex,
      :None,
    )
    typedef Display, :YGDisplay

    Edge = enum(
      :Left,
      :Top,
      :Right,
      :Bottom,
      :Start,
      :End,
      :Horizontal,
      :Vertical,
      :All,
    )
    typedef Edge, :YGEdge

    ExperimentalFeature = enum(
      :WebFlexBasis,
    )
    typedef ExperimentalFeature, :YGExperimentalFeature

    FlexDirection = enum(
      :Column,
      :ColumnReverse,
      :Row,
      :RowReverse,
    )
    typedef FlexDirection, :YGFlexDirection

    Justify = enum(
      :FlexStart,
      :Center,
      :FlexEnd,
      :SpaceBetween,
      :SpaceAround,
    )
    typedef Justify, :YGJustify

    LogLevel = enum(
      :Error,
      :Warn,
      :Info,
      :Debug,
      :Verbose,
      :Fatal,
    )
    typedef LogLevel, :YGLogLevel

    MeasureMode = enum(
      :Undefined,
      :Exactly,
      :AtMost,
    )
    typedef MeasureMode, :YGMeasureMode

    NodeType = enum(
      :Default,
      :Text,
    )
    typedef NodeType, :YGNodeType

    Overflow = enum(
      :Visible,
      :Hidden,
      :Scroll,
    )
    typedef Overflow, :YGOverflow

    PositionType = enum(
      :Relative,
      :Absolute,
    )
    typedef PositionType, :YGPositionType

    PrintOptions = enum(
      :Layout, 1,
      :Style, 2,
      :Children, 4,
    )
    typedef PrintOptions, :YGPrintOptions

    Unit = enum(
      :Undefined,
      :Point,
      :Percent,
      :Auto,
    )
    typedef Unit, :YGUnit

    Wrap = enum(
      :NoWrap,
      :Wrap,
      :WrapReverse,
    )
    typedef Wrap, :YGWrap

  end
end
