# Auto-generated by Rake from Yoga.h
# Do not edit by hand
module YogaLayout
  module Native
    remember_function :YGNodeSetContext, [:YGNodeRef, :pointer], :void
    remember_function :YGNodeGetContext, [:YGNodeRef], :pointer
    remember_function :YGNodeSetMeasureFunc, [:YGNodeRef, :YGMeasureFunc], :void
    remember_function :YGNodeGetMeasureFunc, [:YGNodeRef], :YGMeasureFunc
    remember_function :YGNodeSetPrintFunc, [:YGNodeRef, :YGPrintFunc], :void
    remember_function :YGNodeGetPrintFunc, [:YGNodeRef], :YGPrintFunc
    remember_function :YGNodeSetHasNewLayout, [:YGNodeRef, :bool], :void
    remember_function :YGNodeGetHasNewLayout, [:YGNodeRef], :bool
    remember_function :YGNodeSetNodeType, [:YGNodeRef, :YGNodeType], :void
    remember_function :YGNodeGetNodeType, [:YGNodeRef], :YGNodeType
    remember_function :YGNodeStyleSetDirection, [:YGNodeRef, :YGDirection], :void
    remember_function :YGNodeStyleGetDirection, [:YGNodeRef], :YGDirection
    remember_function :YGNodeStyleSetFlexDirection, [:YGNodeRef, :YGFlexDirection], :void
    remember_function :YGNodeStyleGetFlexDirection, [:YGNodeRef], :YGFlexDirection
    remember_function :YGNodeStyleSetJustifyContent, [:YGNodeRef, :YGJustify], :void
    remember_function :YGNodeStyleGetJustifyContent, [:YGNodeRef], :YGJustify
    remember_function :YGNodeStyleSetAlignContent, [:YGNodeRef, :YGAlign], :void
    remember_function :YGNodeStyleGetAlignContent, [:YGNodeRef], :YGAlign
    remember_function :YGNodeStyleSetAlignItems, [:YGNodeRef, :YGAlign], :void
    remember_function :YGNodeStyleGetAlignItems, [:YGNodeRef], :YGAlign
    remember_function :YGNodeStyleSetAlignSelf, [:YGNodeRef, :YGAlign], :void
    remember_function :YGNodeStyleGetAlignSelf, [:YGNodeRef], :YGAlign
    remember_function :YGNodeStyleSetPositionType, [:YGNodeRef, :YGPositionType], :void
    remember_function :YGNodeStyleGetPositionType, [:YGNodeRef], :YGPositionType
    remember_function :YGNodeStyleSetFlexWrap, [:YGNodeRef, :YGWrap], :void
    remember_function :YGNodeStyleGetFlexWrap, [:YGNodeRef], :YGWrap
    remember_function :YGNodeStyleSetOverflow, [:YGNodeRef, :YGOverflow], :void
    remember_function :YGNodeStyleGetOverflow, [:YGNodeRef], :YGOverflow
    remember_function :YGNodeStyleSetDisplay, [:YGNodeRef, :YGDisplay], :void
    remember_function :YGNodeStyleGetDisplay, [:YGNodeRef], :YGDisplay
    remember_function :YGNodeStyleSetFlex, [:YGNodeRef, :float], :void
    remember_function :YGNodeStyleGetFlex, [:YGNodeRef], :float
    remember_function :YGNodeStyleSetFlexGrow, [:YGNodeRef, :float], :void
    remember_function :YGNodeStyleGetFlexGrow, [:YGNodeRef], :float
    remember_function :YGNodeStyleSetFlexShrink, [:YGNodeRef, :float], :void
    remember_function :YGNodeStyleGetFlexShrink, [:YGNodeRef], :float
    remember_function :YGNodeStyleSetFlexBasisAuto, [:YGNodeRef, :YGEdge], :void
    remember_function :YGNodeStyleSetPosition, [:YGNodeRef, :YGEdge, :float], :void
    remember_function :YGNodeStyleSetPositionPercent, [:YGNodeRef, :YGEdge, :float], :void
    remember_function :YGNodeStyleGetPosition, [:YGNodeRef, :YGEdge], :YGValue
    remember_function :YGNodeStyleSetMargin, [:YGNodeRef, :YGEdge, :float], :void
    remember_function :YGNodeStyleSetMarginPercent, [:YGNodeRef, :YGEdge, :float], :void
    remember_function :YGNodeStyleGetMargin, [:YGNodeRef, :YGEdge], :YGValue
    remember_function :YGNodeStyleSetMarginAuto, [:YGNodeRef, :YGEdge], :void
    remember_function :YGNodeStyleSetPadding, [:YGNodeRef, :YGEdge, :float], :void
    remember_function :YGNodeStyleSetPaddingPercent, [:YGNodeRef, :YGEdge, :float], :void
    remember_function :YGNodeStyleGetPadding, [:YGNodeRef, :YGEdge], :YGValue
    remember_function :YGNodeStyleSetBorder, [:YGNodeRef, :YGEdge, :float], :void
    remember_function :YGNodeStyleGetBorder, [:YGNodeRef, :YGEdge], :float
    remember_function :YGNodeStyleSetWidthAuto, [:YGNodeRef, :YGEdge], :void
    remember_function :YGNodeStyleSetHeightAuto, [:YGNodeRef, :YGEdge], :void
    remember_function :YGNodeStyleSetMinWidth, [:YGNodeRef, :float], :void
    remember_function :YGNodeStyleSetMinWidthPercent, [:YGNodeRef, :float], :void
    remember_function :YGNodeStyleGetMinWidth, [:YGNodeRef], :YGValue
    remember_function :YGNodeStyleSetMinHeight, [:YGNodeRef, :float], :void
    remember_function :YGNodeStyleSetMinHeightPercent, [:YGNodeRef, :float], :void
    remember_function :YGNodeStyleGetMinHeight, [:YGNodeRef], :YGValue
    remember_function :YGNodeStyleSetMaxWidth, [:YGNodeRef, :float], :void
    remember_function :YGNodeStyleSetMaxWidthPercent, [:YGNodeRef, :float], :void
    remember_function :YGNodeStyleGetMaxWidth, [:YGNodeRef], :YGValue
    remember_function :YGNodeStyleSetMaxHeight, [:YGNodeRef, :float], :void
    remember_function :YGNodeStyleSetMaxHeightPercent, [:YGNodeRef, :float], :void
    remember_function :YGNodeStyleGetMaxHeight, [:YGNodeRef], :YGValue
    remember_function :YGNodeStyleSetAspectRatio, [:YGNodeRef, :float], :void
    remember_function :YGNodeStyleGetAspectRatio, [:YGNodeRef], :float
    remember_function :YGNodeLayoutGetLeft, [:YGNodeRef], :float
    remember_function :YGNodeLayoutGetTop, [:YGNodeRef], :float
    remember_function :YGNodeLayoutGetRight, [:YGNodeRef], :float
    remember_function :YGNodeLayoutGetBottom, [:YGNodeRef], :float
    remember_function :YGNodeLayoutGetWidth, [:YGNodeRef], :float
    remember_function :YGNodeLayoutGetHeight, [:YGNodeRef], :float
    remember_function :YGNodeLayoutGetDirection, [:YGNodeRef], :YGDirection
    remember_function :YGNodeLayoutGetHadOverflow, [:YGNodeRef], :bool
    remember_function :YGNodeLayoutGetMargin, [:YGNodeRef, :YGEdge], :float
    remember_function :YGNodeLayoutGetBorder, [:YGNodeRef, :YGEdge], :float
    remember_function :YGNodeLayoutGetPadding, [:YGNodeRef, :YGEdge], :float
  end
end
