# This file is auto-generated by //enums.py
# Do not edit by hand!
module YogaLayout
  module Bindings

    Align = enum(
      :auto,
      :flex_start,
      :center,
      :flex_end,
      :stretch,
      :baseline,
      :space_between,
      :space_around,
    )
    typedef Align, :YGAlign

    Dimension = enum(
      :width,
      :height,
    )
    typedef Dimension, :YGDimension

    Direction = enum(
      :inherit,
      :ltr,
      :rtl,
    )
    typedef Direction, :YGDirection

    Display = enum(
      :flex,
      :none,
    )
    typedef Display, :YGDisplay

    Edge = enum(
      :left,
      :top,
      :right,
      :bottom,
      :start,
      :end,
      :horizontal,
      :vertical,
      :all,
    )
    typedef Edge, :YGEdge

    ExperimentalFeature = enum(
      :web_flex_basis,
    )
    typedef ExperimentalFeature, :YGExperimentalFeature

    FlexDirection = enum(
      :column,
      :column_reverse,
      :row,
      :row_reverse,
    )
    typedef FlexDirection, :YGFlexDirection

    Justify = enum(
      :flex_start,
      :center,
      :flex_end,
      :space_between,
      :space_around,
    )
    typedef Justify, :YGJustify

    LogLevel = enum(
      :error,
      :warn,
      :info,
      :debug,
      :verbose,
      :fatal,
    )
    typedef LogLevel, :YGLogLevel

    MeasureMode = enum(
      :undefined,
      :exactly,
      :at_most,
    )
    typedef MeasureMode, :YGMeasureMode

    NodeType = enum(
      :default,
      :text,
    )
    typedef NodeType, :YGNodeType

    Overflow = enum(
      :visible,
      :hidden,
      :scroll,
    )
    typedef Overflow, :YGOverflow

    PositionType = enum(
      :relative,
      :absolute,
    )
    typedef PositionType, :YGPositionType

    PrintOptions = enum(
      :layout, 1,
      :style, 2,
      :children, 4,
    )
    typedef PrintOptions, :YGPrintOptions

    Unit = enum(
      :undefined,
      :point,
      :percent,
      :auto,
    )
    typedef Unit, :YGUnit

    Wrap = enum(
      :no_wrap,
      :wrap,
      :wrap_reverse,
    )
    typedef Wrap, :YGWrap

  end
end
